### ISSUE TITLE
could not run the media player 

### ISSUE THREAD

**Issue by akash-arch** [ant6/GestureMusicPlayer#3]
the code is working fine but can you tell me how am i suppose to load the media player to demonstrate this.

**Comment by antnieszka** [comment]
Hi,
try to run VLC first and then the code. For quick testing you can just start the python interpreter in project directory, import commands and run some to test communication with VLC. If that fails... it may be some issue with vlc-ctrl.

```py
import commands
play()
```

**Comment by akash-arch** [comment]
C:\Users\Star-Lord\Downloads\GestureMusicPlayer-master>vlc.py
Usage: C:\Users\Star-Lord\Downloads\GestureMusicPlayer-master\vlc.py [options] <movie_filename>
Once launched, type ? for help.

Build date: Tue Nov 29 10:26:53 2016 (0x0)
LibVLC version: 2.2.4 Weatherwax (0x2020400)
LibVLC compiler: gcc version 4.9.2 (GCC)
Plugin path: C:\Program Files\VideoLAN\VLC



this happens when i run  vlc.py

**Comment by antnieszka** [comment]
By VLC i mean downloading a media player named so: https://www.videolan.org/vlc/index.pl.html
No the vlc.py :)

When I created this project I focused on supporting this one media player in particular, because it was easier on linux. Now when I think about it, it should send some media-keys signals - that would be more generic...

**Comment by UtkarshK10** [comment]
not working on windows in vlc player

**Comment by UtkarshK10** [comment]
could you tell me what command is for what

**Comment by antnieszka** [comment]
As I wrote in #2 there are now issues with vlc-ctrl. After investigation it looks like there is a better alternative to work with vlc https://wiki.videolan.org/Python_bindings/

But honestly, you just switch implementation of commands in `commands.py` to anything you like, windows media player, whatever suits you. I made this demo on linux and it works fine on it. The commands dont work out of the box on windows because of vlc-crtl library.
